language: node_js
node_js:
- node
- '5.11'
- '4.4'
- iojs
- '0.12'
matrix:
  fast_finish: true
sudo: false
script:
- npm run ci
before_deploy:
- npm run build
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: ZvlyiQz46osG3Zwjhwmbl4bJCHd2o8LalFI5I8i3ar2UQqRnhTnV5fqnooRyQ2NysbQMZkW6UlYZU6WZZMyEjyG/z5x9hB+RcBwwGq2xxdSPoG55DktoXRlbjGQFzhiHtB0wTKQJiQk7wQt/7EjmEe1cNv9OJyvBCN8i8ROhU8Sg/uEDdh9Iit8xG6rCEXiW7y2e/Uq2KnT8B2gZuAdR3YVPeM2DN5j8gYGTzJfXmS1KJTNMV02eqA0SkZ6vQ6BkQVO9fK1AjyQB/fi2ddo0beczaWwTTRO8TSUTAaRNNvw5V0oitBdWrhNwL0F87TGcOAzoCU3MQ1QY99Sa6Db7oLVsEMs1le8vVj1XrVdYc53a/UVdI/O5ks/ayASABGQPekQt2aXMzhVYCD8//DqAUgTalDH+m18S2t/6/Cz4unsEzP80O2BEl8AwP1ajfpWeT7usHbr1BLxWfHF7l2bvsaCEbvDDbxgSid4B6j5o7hv8PumljiVotdFWagtd9XdfKswp82hZrrpBrAusJGX0kkIA26G970APVzYBySmpjdEMDH8OdDCWA8YzvSKW4zYMi2jjSTG70felJGMIGDP6XTyC94mgsc7aUhjAz3Yjfubjw8l72VWf9mBPCs7IqyiYtQvFhYPuXDyeugiRVbUM7tfnsUnflvO8FshagbQMsJs=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/steeplejack-express
